# Generated by Django 5.0.2 on 2024-03-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('number_of_pages', models.IntegerField()),
                ('publication_date', models.DateField(max_length=100)),
                ('category', models.ManyToManyField(to='book.category')),
            ],
        ),
    ]
